# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       headless-keyboard

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Setup app for headless-keyboard layout
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  headless-keyboard.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   pygobject2
Requires:   dbus-python
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Short description of my SailfishOS Application

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
ls %{buildroot}

#rm -rf %{buildroot}

# >> install pre
# << install pre
%qmake5_install

# >> install post

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(755,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/maliit/plugins/com/jolla/custom_headless
%{_datadir}/maliit/plugins/com/jolla
%{_datadir}/dbus-1/services
# >> files
# << files

%post
chmod 755 /usr/bin/headless_keyboard.py
patch -p0 < /usr/share/maliit/plugins/com/jolla/custom_headless/KeyboardBase.patch

%preun
patch -R -p0 < /usr/share/maliit/plugins/com/jolla/custom_headless/KeyboardBase.patch
